name: Asset Release Workflow

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository code
      - name: 👉 Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          submodules: recursive

      # 2. Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3
        with:
          version: 10

      # 3. Setup Node.js
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version-file: '.nvmrc'

      # 4. Install dependencies
      - name: Install PNPM dependencies
        run: pnpm install --frozen-lockfile

      # 5. Build release package
      - name: 📦 Build release package
        run: pnpm build

      # 6. Upload the zipped project as a release asset
      - name: 📤 Upload Release Asset
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        with:
          files: customs-fees-for-woocommerce.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 7. All good
      - name: 🎉 All good
        run: echo "All good!"
